language: node_js
node_js:
- node
env:
-production
script:
- yarn install
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: pGQ2jC2GDntOP5gU3L/hH2RbxCgdzb6enHQ7MnYpJLsctw4rnT/L/KavTEVHi/17jlacLSeVKnrVqoFVC8ygox/pJ+IPhMwbL6Qie1XR9a3dAgKcyWJKh/Vd5I09nrwemnzjWuVcRvNMQrO4D2g9sTLdVh5kAabtDTJ+BCgYigV/KdHH1T1l5Y1n1WpjQK0fU2lLq55LDw7MERaDGAt1riVOPcAyofhuGWwWi/BwTY4DBcDO5Z0+jfWAAjxyoXFscIYKrBip8I/2qKvM8PY+LUl0hVzVuw50FY7wVOTjkRDZv1PB6f2LoAnu+//882mN5JmP3WobABJ+xP3i11+WWp2j5mdXpxrFmA3uFQN3UTrE6FgpQ0NjgtDjdrd0A7YFLRFqEyy4C7O7eifBhLV/AKo9BpqfBYgviU2YD22mck7Hsb9jZFtZ65GMv7lqQuMWY5UlJZWcOKFlupNIq99JSJ/yJHm7+chqZZ29hD1ZdL9nYM5d0vv3SQQnnFXS530dYbeJ2+ix63qk/vfJkY6/xP3dog2swsal84/DL4h5VIi7xWBqHocScc/hExWSZD63YqDlDKAMI3PEpxYKE+Nq2KdQQeb//KYT/b4JfjaekPEWjbwv3jG9MveJZizFG/ATSyO9YURYmCG0VWD9PJSHEIFiBdgZwlr7DCYPyvYmaAM=
  app: radiant-harbor-82176
  on:
    repo: twalton83/my-CV
    branch: development
  skip_cleanup: 'true'
